package:
  name: mrbait
  version: "1.1.3"

source:
  git_url: https://github.com/tkchafin/mrbait.git
  git_rev: v1.1.3

build:
  skip: True  # [win]
  noarch: python

requirements:
  build:
    - python {{PY_VER}}*,>=3.6
    - pandas >=0.22
    - biopython
    - numpy >=1.9
    - pyvcf >=0.6.8
    - networkx >=2.0
    - setuptools
    - blast
    - vsearch
  run:
    - python {{PY_VER}}*,>=3.6
    - pandas >=0.22
    - biopython
    - numpy >=1.9
    - pyvcf >=0.6.8
    - networkx >=2.0
    - blast
    - vsearch

  commands:
    - mrbait.py -h

about:
  home: https://github.com/tkchafin/mrbait
  license: GPLv3
  summary: Universal design of target-enrichment capture probes from genomic data
