package:
  name: mrbait
  version: "1.0.0"

source:
  git_url: https://github.com/tkchafin/mrbait.git
  git_rev: v1.0.0

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - python {{PY_VER}}*,>=3.6
    - multiprocessing >=2.6
    - sqlite3
    - pandas >=0.22
    - biopython
    - numpy
    - vcf_tools
    - networkx >= 2.0

  run:
    - python {{PY_VER}}*,>=3.6
    - multiprocessing >=2.6
    - sqlite3
    - pandas >=0.22
    - biopython
    - numpy
    - vcf_tools
    - networkx >= 2.0

  commands:
    - mrbait.py -h

about:
  home: https://github.com/tkchafin/mrbait
  license: GPLv3
  summary: Universal design of target-enrichment capture probes from genomic data
